logging:
  level:
    pl.aagenda: DEBUG
    org.neo4j.ogm.drivers.bolt.request.BoltRequest: DEBUG

server:
  port: 8081

spring:
  application:
    name: data-storage
  data:
    neo4j:
      username: neo4j
      password: password

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'