version: '3.1'
services:

  data-storage:
    image: familyguard/data-storage
    build:
      context: ./data-storage
    ports:
     - "8081:8081"
    depends_on:
      - neo4j

  uaa:
    image: familygaurd/uaa
    build:
      context: ./uaa
    ports:
      - "9999:9999"
    depends_on:
      - postgresql

  neo4j:
    image: neo4j:3.3
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "/opt/familyguard/neo4j/data:/data"
      - "/opt/familyguard/neo4j/logs:/logs"

  postgresql:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - "/opt/familyguard/postgresql:/var/lib/postgresql"