version: '3.1'
services:

  data-storage:
    image: familyguard/data-storage
    build:
      context: ./data-storage
    ports:
     - "8081:8081"
    depends_on:
      - neo4j

  artifact-storage:
    image: familyguard/artifact-storage
    build:
      context: ./artifact-storage
    ports:
      - "8082:8082"
    depends_on:
      - mongo

  uaa:
    image: familygaurd/uaa
    build:
      context: ./uaa
    ports:
      - "9999:9999"
    depends_on:
      - postgresql

  neo4j:
    image: neo4j:4.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "/opt/familyguard/neo4j/data:/var/lib/neo4j/data"
      - "/opt/familyguard/neo4j/logs:/logs"
    environment:
      NEO4J_AUTH: neo4j/password

  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
    volumes:
      - "/opt/familyguard/mongo/data:/data/db"

  postgresql:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - "/opt/familyguard/postgresql:/var/lib/postgresql"
