version: '3.1'
services:

  data-storage:
    image: familyguard/data-storage
    build:
      context: ./data-storage
    ports:
      - "8081:8081"
    depends_on:
      - neo4j

  artifact-storage:
    image: familyguard/artifact-storage
    build:
      context: ./artifact-storage
    ports:
      - "8082:8082"
    depends_on:
      - mongo

  uaa:
    image: familygaurd/uaa
    build:
      context: ./uaa
    ports:
      - "9999:9999"
    depends_on:
      - postgresql

  neo4j:
    image: neo4j:3.3
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "/opt/familyguard/neo4j/data:/data"
      - "/opt/familyguard/neo4j/logs:/logs"

  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
    volumes:
      - "/opt/familyguard/mongo/data:/data/db"

  postgresql:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - "/opt/familyguard/postgresql:/var/lib/postgresql"

  zookeeper:
    image: 'bitnami/zookeeper:3.5.5'
    ports:
      - '2181:2181'
      - '9999:8080'
    volumes:
      - 'zookeeper_data:/bitnami'
#      - '/tmp/familyguard:/bitnami'
#      - '/opt/familyguard/zookeeper:/bitnami/zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:2.3.0'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
#      - '/tmp/familyguard:/bitnami'
#      - '/opt/familyguard/kafka:/bitnami/kafka'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local